### PR TITLE
Fix message cropping

### PR DESCRIPTION
**Pull request by lumapools**
It started when an alien device did what it did
It stuck itself upon my wrist with secrets that it hid
Now I've got superpowers I'm no ordinary kid
I'm Ben 10
So if you see me you might be in for a big surprise
I'll turn into an alien before your very eyes
I'm slimy, creepy, fast and strong
I'm every shape and size
I'm Ben 10
Armed with powers I'm on the case
Fighting off evil from earth or space
I'll never stop till I makes them pay
'Cause he's the baddest kid to ever save day
Ben 10
B-B-B-Ben
B-B-B-Ben

Screenshot from 2021-06-03 21-41-30

Riff Raf in the building, peach panther ready to strike!

### CODE REVIEW

**Review by Superdoude1999 — CHANGES_REQUESTED** [review]
Love you Ben! 💟

**Review by betrisey — APPROVED** [review]

**Review by cronokirby — APPROVED** [review]
yes Yes YES

**Review by Superdoude1999 — APPROVED** [review]
Thank you, I love you ❤️

**Review by bafavre — APPROVED** [review]
Go ahead Mr. Joestar

**Pull request merged**
