### PR TITLE
Discount search

### LINKED ISSUE #265: Seeing Discounted Items
As a Buyer, I want to see items that are currently on sale, in order to find good deals

### LINKED ISSUE #274: Can search only discounted items

### PR DESCRIPTION
**Pull request by bafavre**
Fixes #274 
Fixes #265 

We can now search to find only the discounted items with a checkbox.

### CODE REVIEW

**Review by cronokirby — APPROVED** [review]
This look super simple and effective to me!

**Review by lumapools — COMMENTED** [review]
Very nice! Would it be possible to have the red dot a bit smaller and not touching the border ? I think it would look a bit better this way. Otherwise everything looks good!

**Comment by bafavre** [comment]
Yeah the dot has been changed in the other PR that added it, you can check it here : https://github.com/Sharingang/Sharingang-Android/pull/275

**Comment by lumapools** [comment]
Oh didn't see that, oops. All good then!

**Review by lumapools — APPROVED** [review]

**Pull request merged**
